/// Must stay in sync with the `area` check constraint on the
/// `wholesalers`/`mechanics` tables (see the Supabase migrations
/// `wholesalers_and_khata_ledger` / `mechanics_and_wallet_ledger`).
const kKpkAreas = <String>[
  'Abbottabad',
  'Alpuri',
  'Bahrain',
  'Bannu',
  'Batkhela',
  'Buner',
  'Charsadda',
  'Chitral',
  'Dera Ismail Khan',
  'Dir (Lower)',
  'Dir (Upper)',
  'Hangu',
  'Haripur',
  'Karak',
  'Kohat',
  'Lakki Marwat',
  'Malakand',
  'Mansehra',
  'Mardan',
  'Mingora',
  'Nowshera',
  'Parachinar',
  'Peshawar',
  'Risalpur',
  'Saidu Sharif',
  'Shabqadar',
  'Swabi',
  'Tank',
  'Timergara',
  'Topi',
  'Other',
];
