create table public.mechanics (
  id uuid primary key default gen_random_uuid(),

  full_name text not null
    check (char_length(full_name) between 2 and 100),

  -- 11 normalized digits (03001234567); the UI formats the dash in.
  phone text not null
    check (phone ~ '^03[0-9]{9}$'),

  cnic text
    check (cnic is null or cnic ~ '^[0-9]{5}-[0-9]{7}-[0-9]$'),

  area text not null
    check (area in (
      'Abbottabad', 'Alpuri', 'Bahrain', 'Bannu', 'Batkhela', 'Buner',
      'Charsadda', 'Chitral', 'Dera Ismail Khan', 'Dir (Lower)',
      'Dir (Upper)', 'Hangu', 'Haripur', 'Karak', 'Kohat',
      'Lakki Marwat', 'Malakand', 'Mansehra', 'Mardan', 'Mingora',
      'Nowshera', 'Parachinar', 'Peshawar', 'Risalpur', 'Saidu Sharif',
      'Shabqadar', 'Swabi', 'Tank', 'Timergara', 'Topi', 'Other'
    )),

  address text check (address is null or char_length(address) <= 200),

  photo_storage_path text
    check (photo_storage_path is null or char_length(photo_storage_path) between 1 and 500),
  photo_file_size_bytes integer
    check (photo_file_size_bytes is null or (photo_file_size_bytes > 0 and photo_file_size_bytes <= 5242880)),
  photo_mime_type text
    check (photo_mime_type is null or photo_mime_type in ('image/jpeg', 'image/png', 'image/webp')),

  is_active boolean not null default true,
  deactivated_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,

  constraint mechanics_phone_unique unique (phone),
  constraint mechanics_cnic_unique unique (cnic),
  constraint mechanics_photo_storage_path_unique unique (photo_storage_path)
);

create index mechanics_full_name_idx on public.mechanics (full_name);
create index mechanics_area_idx on public.mechanics (area);
create index mechanics_is_active_idx on public.mechanics (is_active) where is_active = true;
create index mechanics_created_by_idx on public.mechanics (created_by);
create index mechanics_updated_by_idx on public.mechanics (updated_by);

create trigger mechanics_updated_at
before update on public.mechanics
for each row execute function public.handle_updated_at();

create table public.wallet_transactions (
  id uuid primary key default gen_random_uuid(),

  mechanic_id uuid not null
    references public.mechanics(id) on delete restrict,

  transaction_type text not null
    check (transaction_type in (
      'opening',
      'scan',
      'withdrawal_pending',
      'withdrawal_paid',
      'withdrawal_confirmed',
      'withdrawal_disputed',
      'withdrawal_auto_confirmed',
      'withdrawal_refund'
    )),

  amount_pkr numeric(12, 2) not null,

  entry_date date not null default current_date,

  reference_id uuid,
  reference_text text check (reference_text is null or char_length(reference_text) <= 200),

  recorded_by_kind text not null default 'system'
    check (recorded_by_kind in ('system', 'mechanic', 'staff')),
  recorded_by uuid references public.profiles(id) on delete set null,

  seq bigint generated by default as identity,

  created_at timestamptz not null default now(),

  constraint wallet_transactions_recorded_by_on_staff
    check (
      (recorded_by_kind = 'staff' and recorded_by is not null)
      or (recorded_by_kind <> 'staff' and recorded_by is null)
    )
);

create unique index wallet_transactions_seq_idx on public.wallet_transactions (seq);
create index wallet_transactions_mechanic_idx on public.wallet_transactions (mechanic_id, seq desc);
create index wallet_transactions_type_idx on public.wallet_transactions (transaction_type);
create index wallet_transactions_reference_idx on public.wallet_transactions (reference_id);
create index wallet_transactions_recorded_by_idx on public.wallet_transactions (recorded_by);

create or replace function public.block_wallet_transaction_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'wallet_transactions is append-only. Insert a reversing entry instead.'
    using errcode = '0A000';
end;
$$;

create trigger wallet_transactions_no_update
before update or delete on public.wallet_transactions
for each row execute function public.block_wallet_transaction_mutation();

alter table public.mechanics enable row level security;
alter table public.wallet_transactions enable row level security;

create policy mechanics_select_staff on public.mechanics
for select to authenticated
using ((select private.is_staff()));

create policy mechanics_insert_staff on public.mechanics
for insert to authenticated
with check ((select private.is_staff()));

create policy mechanics_update_staff on public.mechanics
for update to authenticated
using ((select private.is_staff()))
with check ((select private.is_staff()));

create policy mechanics_delete_staff on public.mechanics
for delete to authenticated
using ((select private.is_staff()));

create policy wallet_transactions_select_staff on public.wallet_transactions
for select to authenticated
using ((select private.is_staff()));

create policy wallet_transactions_insert_staff on public.wallet_transactions
for insert to authenticated
with check ((select private.is_staff()));

grant select, insert, update, delete on public.mechanics to authenticated;
grant select, insert on public.wallet_transactions to authenticated;
