-- ============================================================
-- Deterministic ledger ordering
--
-- created_at defaults to now(), which in Postgres is the
-- transaction timestamp -- so entries written in a single
-- transaction all share one value and sort arbitrarily against
-- each other. The Khata tab renders a running-balance column, so
-- an ambiguous order shows the balance jumping around.
--
-- seq gives the ledger a monotonic insertion order to sort by.
-- Order khata_entries by seq, never by created_at.
-- ============================================================

alter table public.khata_entries
  add column seq bigint generated by default as identity;

create unique index khata_entries_seq_idx on public.khata_entries (seq);

-- Replaces the (wholesaler_id, created_at desc) index: every
-- ledger read is "this wholesaler's entries in ledger order".
drop index public.khata_entries_wholesaler_idx;
create index khata_entries_wholesaler_idx
  on public.khata_entries (wholesaler_id, seq desc);
