-- ============================================================
-- Dev-only Send SMS Hook: no SMS provider account exists yet, so
-- this replaces real delivery. It logs the phone + the REAL OTP
-- GoTrue generated into dev_otp_log, which staff can read to log
-- in during development. Remove this hook (dashboard toggle) and
-- this migration's objects once a real SMS provider is connected.
--
-- Must be shaped exactly (jsonb) returns jsonb -- that's the
-- contract the Auth Hooks picker in the dashboard looks for.
-- ============================================================

create table public.dev_otp_log (
  id bigint generated by default as identity primary key,
  phone text not null,
  otp text not null,
  created_at timestamptz not null default now()
);

create index dev_otp_log_phone_idx on public.dev_otp_log (phone, created_at desc);

alter table public.dev_otp_log enable row level security;

-- Staff-only read; nothing else gets a policy, so anon/authenticated
-- can neither insert nor read -- only the SECURITY DEFINER function
-- below (and staff, for reading) can touch this table.
create policy dev_otp_log_select_staff on public.dev_otp_log
for select to authenticated
using ((select private.is_staff()));

create or replace function public.send_sms(event jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.dev_otp_log (phone, otp)
  values (event->'user'->>'phone', event->'sms'->>'otp');

  return '{}'::jsonb;
end;
$$;

revoke all on function public.send_sms(jsonb) from public;
revoke execute on function public.send_sms(jsonb) from anon, authenticated;
grant execute on function public.send_sms(jsonb) to supabase_auth_admin;
